image: java:openjdk-8

before_script:
  - mkdir -p /cache/repository /cache/wrapper /root/.m2
  - ln -s /cache/repository /root/.m2/repository
  - ln -s /cache/wrapper /root/.m2/wrapper

build:
  script:
    - ./mvnw install -Dgpg.skip=true
    
